version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "5000:8000"
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - tibber_challenge/.env.db

volumes:
  postgres_data: